---
title: spektrum
timezone: UTC
collections:
  ble:
    title: Ble
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    Name: 10
    Price: 20
  uploads:
    title: Uploads
    output: true
  snip:
    title: snip
    output: true
    price:
      ee: 
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
